### ISSUE TITLE
MKS_ScanOMatic will be deprecated

### ISSUE THREAD

**Issue by Olympic1** [DuoDex/CrowdSourcedScience#17]
In the next release of MKS/OKS the science reports of the ScanOMatic will be deprecated. So our support for that will have to removed when the new MKS release is available

https://github.com/BobPalmer/MKS/commit/990756a453be8a9537d8ba01bcd70c0e112eb577

**Comment by Olympic1** [comment]
It is already released

**Comment by madsailor** [comment]
Sounds good.  The only file that has content is the one in 000_default. The rest are just framework and can be deleted. Maybe we can ask RoverDude to relicense these reports as CC0 so we can reuse them. Else they can be deleted as well.

**Comment by harryyoung** [comment]
I Cleaned out MKS support. We just need to ask RoverDude for clearance to find new homes for his reports

**Comment by Olympic1** [comment]
Those reports for MKS were originally written by me, so actually they are under my license and RoverDude included them in his mod. So actually I should give clearance to the reports.

So by this:
> To the extent possible under law, Olympic1 has waived all copyright and related or neighboring rights to MKS_ScanOMatic science reports. This work is published from: Belgium.

**Comment by harryyoung** [comment]
Ah, l in that case let me fix my fork up.
