### ISSUE TITLE
Two questions 

### ISSUE THREAD

**Issue by ImAHungryMan** [DuoDex/CrowdSourcedScience#24]
1) Is it within the scope/capabilities of this mod to change biome names? It might make it easier to create unique blurbs if the biome names were a bit more interesting and varied.

2) How does this mod react with existing ScienceDefs? For example, if I were to add mod support and that mod already has its own ScienceDefs, would I have to take any extra steps to ensure compatibility?

**Comment by Olympic1** [comment]
1) It's not possible to change the biome names with this mod. This only adds reports for the existing biomes.

2) We prefer supporting mods that have (almost) no ScienceDefs. But if you suggest a mod you want to add support for, we can take a look.

**Comment by ImAHungryMan** [comment]
1) Understood.

2) I was looking at DMagic Orbital Science actually. And I believe some planet packs come with their own configs. Is it something that can be done using guidance from the wiki? If so, I can do it myself to spare you guys some effort.

**Comment by madsailor** [comment]
It's possible to add support for any experiment or planet using the guide in the wiki.  The line ```!RESULTS {}``` added in the default_000 folder tells MM to discard all existing reports.  If it's possible to skip this and just add our new reports with ```%RESULTS```, great. Otherwise we have to host a copy of all the existing reports, which for DMOS is a lot of reports.  harryyoung (or sarbian/MM experts) would know whether this is possible.

**Comment by ImAHungryMan** [comment]
Ohh okay. So it makes more sense to just leave DMOS and other mods with lots of reports alone then? 

Unless %RESULTS can peacefully integrate our reports with theirs?

**Comment by madsailor** [comment]
Just did some testing, and it IS possible to add our reports on top without clobbering what's already there.  I've updated the wiki, we just needed a small change in the file added to 000_default.  Now you can add support for DMOS following those instructions without worrying about conflicts/losing original reports from DMOS (or any other mod).  And we don't have to host their reports. Thanks for the interest!

**Comment by ImAHungryMan** [comment]
Ah thanks I noticed that wiki edit and got excited. 

So for future reference % tacks on your edits without removing the existing stuff?

**Comment by madsailor** [comment]
Yes.

**Comment by DuoDex** [comment]
Just like @madsailor said.

**Comment by ImAHungryMan** [comment]
Thank you all!

**Comment by Olympic1** [comment]
The % syntax checks if there is a category called ``RESULTS`` if it exists it will add the reports to it, if it doesn't esxist it will make the category ``RESULTS``
