### ISSUE TITLE
License confusion?

### ISSUE THREAD

**Issue by SkyMarshal** [DuoDex/CrowdSourcedScience#37]
It seems that you are providing the Creative Commons 0 1.0 Universal license with the repository... yet you claim it is licensed under the Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International license?  It looks like you wish contributions to be licensed under the CC0 license, which, IIRC, you can do using a Contributor License Agreement ([which probably isn't required for this project, but here's a site for that](https://www.clahub.com/)) or you could set up a CONTRIBUTING.md file, which [will prompt contributors to review the guidelines within.](https://github.com/blog/1184-contributing-guidelines)

I'll slap together a PR for the latter in a few just in case.

**Comment by DuoDex** [comment]
Take a look at the Readme.md file, I think it has everything needed.

I suppose I could have set up a Contributing.md file, but for this project I didn't think it was big enough to merit something like that.

**Comment by SkyMarshal** [comment]
I get that, but you're supposed to distribute the license of the work, not the license of contributions to the work, IIRC.

**Comment by SkyMarshal** [comment]
Either way, I've opened PR #38 as a proposed fix for both.

**Comment by DuoDex** [comment]
#38 deals with this, thank you.

**Comment by madsailor** [comment]
It seems like the new CONTRIBUTING.md covers ground that is already covered in the wiki.  Wouldn't it make sense to just have CONTRIBUTING.md link to the wiki, so that contributors can navigate to the sections that are pertinent to them, rather than being prompted with all the info on one page (only some of which will be relevant to their contribution)?

**Comment by SkyMarshal** [comment]
This is true, but I like having information like that accessible both on and offline.  You'll notice that the "How to contribute.txt" file was removed with that PR, as I had merged it and some wiki info into the CONTRIBUTING.md file.

**Comment by madsailor** [comment]
I hadn't considered offline use.  Perhaps we could consolidate the wiki text into a revised contribute.txt for offline use.  The rewrite in CONTRIBUTING.md just seems to be redundant (and potentially confusing) to me.  There is very useful info in CONTRIBUTING.md, I just feel that it would be better served to add that info to the existing wiki and then consolidate the updated wiki into a new contribute.txt for offline use.  I created a pull request before reading your response that alters CONTRIBUTING to point to the wiki.  DuoDex can decide if this is the way to go, and if so, we can add a revised contribute.txt.
