### ISSUE TITLE
Incompatible with Kemini?

### ISSUE THREAD

**Issue by mwerle** [DuoDex/CrowdSourcedScience#56]
This mod seems to stuff up the "Review Experiment" dialog for Kemini experiments.

See https://github.com/mwerle/OrbitalMaterialScience/issues/15 and https://github.com/mwerle/OrbitalMaterialScience/issues/16

Any ideas as to what the cause might be? Anything I can do to fix it on the Kemini side?

Was testing using KSP1.3.1 today.

**Comment by Olympic1** [comment]
@mwerle can you check with the latest version?

**Comment by mwerle** [comment]
Hi @Olympic1 - looks like your latest version hasn't resolved this issue.

I installed CSS v4.1.1 (via CKAN - but I checked that your latest release version on GitHub has the same version number), then tried running a Kemini experiment.

When I finalize the experiment, the results dialog just shows the experiment name + "Acquired" instead of the actual results string.

```
Kemini TEST Experiment from Kerbin's surface:
Kemini TEST Experiment: TEST Data Acquired
```
instead of:
```
Kemini TEST Experiment from Kerbin's surface:
The Kemini Lab aboard this spacecraft appears
to be fully functional. Time to run a real
experiment!
```

When I uninstall CrowdSourcedScience again, the experiment works as expected (reloading from the same save so nothing else has changed).

**Comment by mwerle** [comment]
Sorry; closed by mistake.

**Comment by Olympic1** [comment]
Can you try again without the `ScienceFixer.dll`?

**Comment by mwerle** [comment]
With ScienceFixer.dll disabled it works; I didn't even need to re-run the experiment, reviewing showed the correct results string (but I re-loaded and re-ran it anyway just to double-check).

**Comment by mwerle** [comment]
What I can't understand is -why- it breaks it. I've looked through the ScienceFixer code before and there's nothing there which could break the science definitions of Kemini.

As you can see, it's a perfectly normal definition:
```
EXPERIMENT_DEFINITION
{
	id = NE_KeminiTEST
	<snip>
	RESULTS
	{
		default = The Kemini Lab aboard this spacecraft appears to be fully functional. Time to run a real experiment!
	}
}
```

**Comment by mwerle** [comment]
Actually, I think commit e1fb574 broke it because now all "default" entries are removed as well as entries not ending in "*". This means KSP prints a generated result string.

What you want to do is add "default" entries and entries ending in "*" directly into the results, and append "*" to the rest.

I'll see about making a pull request later.
