### ISSUE TITLE
Fix for Module Manage 3.0+

### ISSUE THREAD

**Issue by apowers** [DuoDex/CrowdSourcedScience#57]
Module Manage 3.0+ fixed an undocumented bug in how experiments are accessed.
```
@EXPERIMENT_DEFINITION[*]
```
Should now be just
```
@EXPERIMENT_DEFINITION
```
https://forum.kerbalspaceprogram.com/index.php?/topic/50533-131-module-manager-301-dec-6th-2017-early-christmas-gift/&do=findComment&comment=3237686

**Comment by Olympic1** [comment]
I'm on it, thanks for letting us know

**Comment by Olympic1** [comment]
Fixed in e1c9837
