### ISSUE TITLE
Awesome science report about Mystery Goo on Eeloo

### ISSUE THREAD

**Issue by madsailor** [DuoDex/CrowdSourcedScience#8]
Please add "As the fine ice crystals kicked up by your landing on the surface slowly gather on the the top of the container, you gingerly tap at the Goo with your finger, expecting it to shatter at any moment" to planets/eeloo/glaciers/mysteryGoo.cfg.

(This is the example I used on the Fan Works thread.  Thought it would be useful to add here.)

**Comment by DuoDex** [comment]
Added and closed.
