### ISSUE TITLE
Wiki Update

### ISSUE THREAD

**Issue by madsailor** [DuoDex/CrowdSourcedScience#9]
I  added a wiki to my fork of your repo based on your new wiki.  Using a local editor I clarified the process for adding science reports, adding new experiments, adding new planets, and added a list of valid eID/situation combinations.  Feel free to clone it, change internal 'madsailor' references to 'DuoDex', and add it to your repo if you like the changes, as I can't do it myself.

**Comment by DuoDex** [comment]
Not my wiki that I made, @Olympic1 made it.

**Comment by madsailor** [comment]
OK.  Hope he finds the changes useful.

**Comment by Olympic1** [comment]
@harryyoung made it, I just fixed some stuff

**Comment by Olympic1** [comment]
Updated the wiki
